apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
  labels:
    app: catalogue
spec:
  replicas: 1
  #minReadySeconds: 10
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: localhost:5000/catalogue
        ports:
        - containerPort: 8080
        #env:
        #- name: ENV_NAME
        #  valueFrom:
        #    configMapKeyRef:
        #      name: metadataName
        #      key: key-name
        #- name: SEC_ENV_NAME
        #  valueFrom:
        #    secretKeyRef:
        #      name: metadataName
        #      key: key-password